Update swift.yml

diff --git a/.github/workflows/swift.yml b/.github/workflows/swift.yml
--- a/.github/workflows/swift.yml
+++ b/.github/workflows/swift.yml
@@ -1,17 +1,25 @@
-# This workflow will build a Swift project
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
-
-name: Swift
+name: Docs
 
 on:
   push:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]
+  workflow_dispatch:
+
+# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
+permissions:
+  contents: read
+  pages: write
+  id-token: write
+
+# Allow one concurrent deployment
+concurrency:
+  group: "pages"
+  cancel-in-progress: true
 
 jobs:
   build:
-
     runs-on: macos-latest
 
     steps:
@@ -28,13 +36,37 @@ jobs:
     steps:
     - uses: actions/checkout@v4
     - name: Setup Swift
-      run: |
-        echo "Setup Swift Environment"
-        # Add any necessary setup commands here
-    - uses: fwcd/swift-docc-action@v1
+      uses: swift-actions/setup-swift@v1
+      with:
+        swift-version: '5.7'
+    - name: Generate Docs
+      uses: fwcd/swift-docc-action@v1
       with:
         target: GoogleScholarSwift
-        output: ./docs
-        hosting-base-path: GoogleScholarSwift
-        disable-indexing: 'true'
+        output: ./public
         transform-for-static-hosting: 'true'
+        disable-indexing: 'true'
+        hosting-base-path: GoogleScholarSwift
+    - name: Check Documentation Generation
+      run: |
+        if [ -d "./public" ] && [ "$(ls -A ./public)" ]; then
+          echo "Documentation generated successfully."
+        else
+          echo "Documentation generation failed."
+          exit 1
+        fi
+    - name: Upload artifact
+      uses: actions/upload-pages-artifact@v1
+      with:
+        path: ./public
+
+  deploy:
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+    runs-on: ubuntu-latest
+    needs: generate-docs
+
+    steps:
+    - name: Deploy Docs
+      uses: actions/deploy-pages@v1
